{
 "title": "ZFS pool all queues read/write latency",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(node_zpool_latency_vdev_tot_r_lat_histo_seconds_bucket, instance)"
   },
   {
    "name": "pool_name",
    "label": "poolname",
    "query": "label_values(node_zpool_latency_vdev_tot_r_lat_histo_seconds_bucket, name)"
   }
  ]
 },
 "panels": [
  { "title": "total reads/writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool top-level reads: pool=$pool_name",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_tot_r_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pool top-level writes: pool=$pool_name",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_tot_w_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "ZIO scheduler queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Sync read queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_sync_r_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Async read queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_async_r_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scrub read queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_scrub_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_disk_r_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sync write queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_sync_w_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Async write queue",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_async_w_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_zpool_latency_vdev_disk_w_lat_histo_seconds_bucket{instance=~\"^$hostname:.*\",name=\"$pool_name\", le=~\"^[0-9].*\"}[5m]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{le}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "About ZFS pool all queues read/write latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "About ZFS pool all queues read/write latency",
   "type": "text",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 30 },
   "content": "I/O requests that are satisfied by accessing pool devices are managed by the ZIO scheduler.\nThe total latency is measured from the start of the I/O to completion by the disk.\nLatency through each queue is shown prior to its submission to the disk queue.\n\nThis view is useful for observing the effects of tuning the ZIO scheduler min and max values\n(see zfs-module-parameters(5) and [ZFS on Linux Module Parameters](https://github.com/zfsonlinux/zfs/wiki/ZFS-on-Linux-Module-Parameters)):\n+ *zfs_vdev_max_active* controls the ZIO scheduler's disk queue depth (do not confuse with the block device's nr_requests)\n+ *zfs_vdev_sync_read_min_active* and *zfs_vdev_sync_read_max_active* control the synchronous queue for reads: most reads are sync\n+ *zfs_vdev_sync_write_min_active* and *zfs_vdev_sync_write_max_active* control the synchronous queue for writes: \nusually metadata or user data depending on the \"sync\" property setting or I/Os that are requested to be flushed\n+ *zfs_vdev_async_read_min_active* and *zfs_vdev_async_read_max_active* control the asynchronous queue for reads: usually prefetches\n+ *zfs_vdev_async_write_min_active* and *zfs_vdev_async_write_max_active* control the asynchronous queue for writes: \nusually the bulk of all writes at transaction group (txg) commit\n+ *zfs_vdev_scrub_min_active* and *zfs_vdev_scrub_max_active* controls the scan reads: usually scrub or resilver"
  },
  {
   "title": "ZIO Scheduler Queue Model",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "content": "graph LR\nA((I/O request)) --> B(sync read queue)\nA --> C(sync write queue)\nA --> D(async read queue)\nA --> E(async write queue)\nA --> F(scrub queue)\nB --> G(disk queue)\nC --> G\nD --> G\nE --> G\nF --> G\nG --> H((disk))\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}